language: php

php:
  - 7.3
  - 7.4

before_script:
  - travis_retry composer self-update --preview
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - codecov
